name: Docker CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Build da imagem Docker
        run: docker build -t devops-pucpr .

      - name: Login no DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push da imagem para DockerHub
        run: docker tag devops-pucpr ${{ secrets.DOCKER_USERNAME }}/devops-pucpr:latest && docker push ${{ secrets.DOCKER_USERNAME }}/devops-pucpr:latest

      - name: Notificar Discord sobre deploy
        run: |
          curl -H "Content-Type: application/json" \
               -d "{\"content\": \"✅ Deploy finalizado com sucesso no DockerHub! Branch: main\"}" \
               ${{ secrets.DISCORD_WEBHOOK }}
