- name: Send notification to Discord
  run: |
    curl -H "Content-Type: application/json" \
         -d '{"content": "✅ Deploy finalizado com sucesso no DockerHub!"}' \
         ${{ secrets.DISCORD_WEBHOOK }}
